version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-typescript"
s3_bucket = "00000000000000000000000000000000000000000000000000000000000"
s3_prefix = "sam-typescript"
region = "ap-northeast-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
